### ISSUE TITLE
Installation instructions are out of date

### ISSUE THREAD

**Issue by distbit0** [polymath-ai/polymath-ai#79]
I have encountered the following issue after the following steps:

- git clone
- setup .env file
- npm install
- npx polymath -c local-knowledge complete --completion-model gpt-3.5-turbo "How long is a piece of string?"

```
pimania@pimania:~/Dev/AGI/polymath-ai$ npx polymath -c local-knowledge complete --completion-model gpt-3.5-turbo "How long is a piece of string?"
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/pimania/Dev/AGI/polymath-ai/core/cli/dist/src/cli.js' imported from /home/pimania/Dev/AGI/polymath-ai/core/cli/index.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by dglazkov** [comment]
Yikes! The install instructions have gotten out of date. Thanks for spotting that.

Meanwhile, you will need to run this bit: https://github.com/polymath-ai/polymath-ai/blob/main/README.md#working-with-monorepo

to get things going. Since we've switched to TypeScript, there needs to be a build step in addition to `npm i`.
